# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

steps: &steps
  working_directory: /gemini-mode
  steps:
    - run: apt update && apt install -y git ssh make
    - checkout
    - run:
        name: Install Packages 
        command: cask install
    - run: 
        name: Execute Tests
        command: cask exec buttercup -L .
        
jobs:
  emacs-27:
    docker:
      - image: silex/emacs:27.1-ci-cask
    <<: *steps
  emacs-26:
    docker:
      - image: silex/emacs:26.3-ci-cask
    <<: *steps

workflows: 
  build:
    jobs:
      - emacs-27
      - emacs-26
